config/routes.rb
#routes.rb

Rails.application.routes.draw do
  root 'api/homes#index'
  namespace :api do
    resources :favorites, only: [:create, :index, :destroy]
    resources :homes do
      get 'filter_homes', on: :collection
    end
  end
  get '/favorites/:user_id', to: 'favorites#index', as: 'user_favorites'
  post '/favorites/add', to: 'favorites#create'
  delete '/favorites/:id', to: 'favorites#destroy', as: 'delete_favorite'

  get '/register', to: 'users#new', as: 'register'
  post '/register', to: 'users#create'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get "/me/user", to: "users#show"
  get "/me/session", to: "sessions#show"

end

app/views/pages/favorites.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'rails-ujs' %>
    <%= stylesheet_link_tag 'homes', media: 'all' %>
    <title>Homes List</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/api/homes">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <% if session[:user_id].present? %>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <%= session[:user_id] %>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <%= link_to "Favorites", user_favorites_path(user_id: session[:user_id]), class: "dropdown-item" %>
                            <div class="dropdown-divider"></div>
                                <%= link_to "Sign out", logout_path, method: :delete, class: "dropdown-item", data: { confirm: "Are you sure you want to log out?" } %>
                            </div>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to 'Register', register_path, class: 'nav-link' %>
                        </li>
                        <li class="nav-item">
                            <%= link_to 'Login', login_path, class: 'nav-link' %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </nav>


        <div class="searchbar-container">
            <div class="search-section">
        <h2 class="search-title">Search Homes</h2>
        <div class="search-parameters">
            <!-- Price -->
            <div class="search-parameter">
                <div class="parameter-title">Price</div>
                <div class="parameter-values">
                    <div class="parameter-value">
                        <label for="min-price">Min:</label>
                        <input type="number" id="minPrice" class="search-input" placeholder="Min Price">
                    </div>
                    <div class="parameter-value">
                        <label for="max-price">Max:</label>
                        <input type="number" id="maxPrice" class="search-input" placeholder="Max Price">
                    </div>
                </div>
            </div>
            <!-- Square Meters -->
            <div class="search-parameter">
                <div class="parameter-title">Sq. Meters</div>
                <div class="parameter-values">
                    <div class="parameter-value">
                        <label for="min-sqm">Min:</label>
                        <input type="number" id="minSqm" class="search-input" placeholder="Min Sq. Meters">
                    </div>
                    <div class="parameter-value">
                        <label for="max-sqm">Max:</label>
                        <input type="number" id="maxSqm" class="search-input" placeholder="Max Sq. Meters">
                    </div>
                </div>
            </div>
            <!-- Construction Year -->
            <div class="search-parameter">
                <div class="parameter-title">Construction Year</div>
                <div class="parameter-values">
                    <div class="parameter-value">
                        <label for="min-year">Min:</label>
                        <input type="number" id="minConstructionyear" class="search-input" placeholder="Min Construction Year">
                    </div>
                    <div class="parameter-value">
                        <label for="max-year">Max:</label>
                        <input type="number" id="maxConstructionyear" class="search-input" placeholder="Max Construction Year">
                    </div>
                </div>
            </div>
        </div>
        <button id="searchButton" class="search-button">Search</button>
    </div>
</div>

<div id="user-id" data-user-id="<%= session[:user_id] %>"></div>


<div class="homes-container">
    <ul id="homesList">
        <!-- JavaScript will populate this list -->
        <% @favorites.each do |home| %>
            <li class="home-item" data-image-url="<%= home.imageurl %>" data-address="<%= home.address %>" data-municipality="<%= home.municipality %>" data-price="<%= home.price %>" data-squaremeters="<%= home.squaremeters %>" data-home-id="<%= home._id %>">
    <!-- Content will be dynamically added by JavaScript -->
</li>

        <% end %>
    </ul>
</div>

<div id="toast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body"></div>
    </div>

    </div>

    <%= javascript_include_tag 'controllers/favorites' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/homes.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'rails-ujs' %>
    <%= stylesheet_link_tag 'homes', media: 'all' %>
    <title>Homes List</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <% if session[:user_id].present? %>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <%= session[:user_id] %>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <%= link_to "Favorites", favorites_path, class: "dropdown-item" %>
                            <div class="dropdown-divider"></div>
                                <%= link_to "Sign out", logout_path, method: :delete, class: "dropdown-item", data: { confirm: "Are you sure you want to log out?" } %>
                            </div>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to 'Register', register_path, class: 'nav-link' %>
                        </li>
                        <li class="nav-item">
                            <%= link_to 'Login', login_path, class: 'nav-link' %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </nav>


        <div class="searchbar-container">
            <div class="search-section">
        <h2 class="search-title">Search Homes</h2>
        <div class="search-parameters">
            <!-- Price -->
            <div class="search-parameter">
                <div class="parameter-title">Price</div>
                <div class="parameter-values">
                    <div class="parameter-value">
                        <label for="min-price">Min:</label>
                        <input type="number" id="minPrice" class="search-input" placeholder="Min Price">
                    </div>
                    <div class="parameter-value">
                        <label for="max-price">Max:</label>
                        <input type="number" id="maxPrice" class="search-input" placeholder="Max Price">
                    </div>
                </div>
            </div>
            <!-- Square Meters -->
            <div class="search-parameter">
                <div class="parameter-title">Sq. Meters</div>
                <div class="parameter-values">
                    <div class="parameter-value">
                        <label for="min-sqm">Min:</label>
                        <input type="number" id="minSqm" class="search-input" placeholder="Min Sq. Meters">
                    </div>
                    <div class="parameter-value">
                        <label for="max-sqm">Max:</label>
                        <input type="number" id="maxSqm" class="search-input" placeholder="Max Sq. Meters">
                    </div>
                </div>
            </div>
            <!-- Construction Year -->
            <div class="search-parameter">
                <div class="parameter-title">Construction Year</div>
                <div class="parameter-values">
                    <div class="parameter-value">
                        <label for="min-year">Min:</label>
                        <input type="number" id="minConstructionyear" class="search-input" placeholder="Min Construction Year">
                    </div>
                    <div class="parameter-value">
                        <label for="max-year">Max:</label>
                        <input type="number" id="maxConstructionyear" class="search-input" placeholder="Max Construction Year">
                    </div>
                </div>
            </div>
        </div>
        <button id="searchButton" class="search-button">Search</button>
    </div>
</div>

        <div class="homes-container">
            <ul id="homesList">
                <!-- JavaScript will populate this list -->
            </ul>
        </div>
    </div>

    <%= javascript_include_tag 'controllers/homes' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>